import SlotContainer from "./SlotContainer";

const Booking = () => {
  const allFacilitiesHours = {
    poolKrWeekday: [
      { time: "0730", active: true },
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
      { time: "1900", active: true },
      { time: "2000", active: true },
    ],
    poolKrWeekend: [
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
    ],
    poolUtownWeekday: [
      { time: "0730", active: true },
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
      { time: "1900", active: true },
      { time: "2000", active: true },
    ],
    poolUtownWeekend: [
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
    ],
    gymKrWeekday: [
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
      { time: "1900", active: true },
    ],
    gymKrWeekend: [],
    gymUscWeekday: [
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
      { time: "1900", active: true },
      { time: "2000", active: true },
    ],
    gymUscWeekend: [
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
    ],
    gymUtownWeekday: [
      { time: "0700", active: true },
      { time: "0800", active: true },
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
      { time: "1900", active: true },
      { time: "2000", active: true },
      { time: "2100", active: true },
    ],
    gymUtownWeekend: [
      { time: "0700", active: true },
      { time: "0800", active: true },
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
      { time: "1900", active: true },
      { time: "2000", active: true },
      { time: "2100", active: true },
    ],
    gymWellnessWeekday: [
      { time: "0700", active: true },
      { time: "0800", active: true },
      { time: "0900", active: true },
      { time: "1000", active: true },
      { time: "1100", active: true },
      { time: "1200", active: true },
      { time: "1300", active: true },
      { time: "1400", active: true },
      { time: "1500", active: true },
      { time: "1600", active: true },
      { time: "1700", active: true },
      { time: "1800", active: true },
      { time: "1900", active: true },
      { time: "2000", active: true },
      { time: "2100", active: true },
    ],
    gymWellnessWeekend: [],
  };

  return (
    <div className="container-vert">
      <SlotContainer hours={allFacilitiesHours.gymUtownWeekday} />
      <SlotContainer hours={allFacilitiesHours.gymUtownWeekday} />
      <SlotContainer hours={allFacilitiesHours.gymUtownWeekday} />
    </div>
  );
};

export default Booking;
